receding: 8
step_time: 0.1
ref_speed: 0.25
device: cpu
time_print: true
collision_threshold: 0.15

robot:
  name: mkmini_acker
  kinematics: acker
  wheelbase: 0.6
  length: 0.84
  width: 0.60
  max_speed: [0.30, 0.4363323129985824]
  max_acce: [0.40, 0.50]

ipath:
  curve_style: dubins
  min_radius: 1.6
  interval: 0.02
  arrive_threshold: 0.5
  close_threshold: 0.2
  ind_range: 10
  arrive_index_threshold: 1

pan:
  iter_num: 2
  dune_max_num: 100
  nrmp_max_num: 10
  dune_checkpoint: REPLACE_WITH_TRAINED_MKMINI_DUNE_CHECKPOINT
  iter_threshold: 0.1

adjust:
  q_s: [0.7, 0.7, 0.2]
  p_u: 1.0
  eta: 10.0
  d_max: 0.8
  d_min: 0.5
  ro_obs: 400
  bk: 0.1
  solver: ECOS

train:
  direct_train: true
  model_name: mkmini_acker
  data_size: 100000
  data_range: [-20.0, -20.0, 20.0, 20.0]
  batch_size: 256
  epoch: 5000
  valid_freq: 100
  save_freq: 500
  lr: 0.00005
  lr_decay: 0.5
  decay_freq: 1500
  save_loss: true
