yhs_can_control_node:
  ros__parameters:
    can_name: can4
    wheel_base: 0.6
    publish_odom_tf: false
    odom_frame_id: odom
    base_frame_id: base_link
    ultrasonic_number: [0, 1, 2, 3, 4, 5, 6, 7]
